# server enable graceful shutdown
server:
  port: 8080
  shutdown: graceful

# graceful shutdown max wait time
spring.lifecycle.timeout-per-shutdown-phase: 20s

# manage port for health / shutdown
management:
  server.port: 8081
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: shutdown

# jdbc demo
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/homs_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: HomsDemo
  password: 123456
  hikari:
    # more see https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby
    minimumIdle: 10
    maximumPoolSize: 100

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.coder4.homs.demo.server.mybatis.dataobject

# jpa demo
spring.jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: validate
  #properties.hibernate:
    #show_sql: true
    #generate_statistics: true

# redis demo
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: "redisdemo"
    lettuce:
      pool:
        max-active: 50
        min-idle: 5

# nacos
nacos.server: 127.0.0.1:8848

# resilience4j
resilience4j:
  circuitbreaker:
    instances:
      getUserById:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
  thread-pool-bulkhead:
    instances:
      getUserByName:
        maxThreadPoolSize: 100
        coreThreadPoolSize: 50
        queueCapacity: 200
  timelimiter:
    instances:
      getUserByName:
        timeoutDuration: 1s
        cancelRunningFuture: true
  rateLimiter:
    instances:
      getUserByIdV2:
        limitForPeriod: 1
        limitRefreshPeriod: 500ms
        timeoutDuration: 0