// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomsDemo.proto

package com.coder4.homs.demo;

public final class HomsDemoOuterClass {
  private HomsDemoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 val1 = 1;</code>
     * @return The val1.
     */
    int getVal1();

    /**
     * <code>int32 val2 = 2;</code>
     * @return The val2.
     */
    int getVal2();
  }
  /**
   * Protobuf type {@code AddRequest}
   */
  public static final class AddRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddRequest)
      AddRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddRequest.newBuilder() to construct.
    private AddRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              val1_ = input.readInt32();
              break;
            }
            case 16: {

              val2_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.class, com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.Builder.class);
    }

    public static final int VAL1_FIELD_NUMBER = 1;
    private int val1_;
    /**
     * <code>int32 val1 = 1;</code>
     * @return The val1.
     */
    @java.lang.Override
    public int getVal1() {
      return val1_;
    }

    public static final int VAL2_FIELD_NUMBER = 2;
    private int val2_;
    /**
     * <code>int32 val2 = 2;</code>
     * @return The val2.
     */
    @java.lang.Override
    public int getVal2() {
      return val2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (val1_ != 0) {
        output.writeInt32(1, val1_);
      }
      if (val2_ != 0) {
        output.writeInt32(2, val2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (val1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val1_);
      }
      if (val2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, val2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.coder4.homs.demo.HomsDemoOuterClass.AddRequest)) {
        return super.equals(obj);
      }
      com.coder4.homs.demo.HomsDemoOuterClass.AddRequest other = (com.coder4.homs.demo.HomsDemoOuterClass.AddRequest) obj;

      if (getVal1()
          != other.getVal1()) return false;
      if (getVal2()
          != other.getVal2()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL1_FIELD_NUMBER;
      hash = (53 * hash) + getVal1();
      hash = (37 * hash) + VAL2_FIELD_NUMBER;
      hash = (53 * hash) + getVal2();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.coder4.homs.demo.HomsDemoOuterClass.AddRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddRequest)
        com.coder4.homs.demo.HomsDemoOuterClass.AddRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.class, com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.Builder.class);
      }

      // Construct using com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        val1_ = 0;

        val2_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddRequest_descriptor;
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddRequest getDefaultInstanceForType() {
        return com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddRequest build() {
        com.coder4.homs.demo.HomsDemoOuterClass.AddRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddRequest buildPartial() {
        com.coder4.homs.demo.HomsDemoOuterClass.AddRequest result = new com.coder4.homs.demo.HomsDemoOuterClass.AddRequest(this);
        result.val1_ = val1_;
        result.val2_ = val2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.coder4.homs.demo.HomsDemoOuterClass.AddRequest) {
          return mergeFrom((com.coder4.homs.demo.HomsDemoOuterClass.AddRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.coder4.homs.demo.HomsDemoOuterClass.AddRequest other) {
        if (other == com.coder4.homs.demo.HomsDemoOuterClass.AddRequest.getDefaultInstance()) return this;
        if (other.getVal1() != 0) {
          setVal1(other.getVal1());
        }
        if (other.getVal2() != 0) {
          setVal2(other.getVal2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.coder4.homs.demo.HomsDemoOuterClass.AddRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.coder4.homs.demo.HomsDemoOuterClass.AddRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int val1_ ;
      /**
       * <code>int32 val1 = 1;</code>
       * @return The val1.
       */
      @java.lang.Override
      public int getVal1() {
        return val1_;
      }
      /**
       * <code>int32 val1 = 1;</code>
       * @param value The val1 to set.
       * @return This builder for chaining.
       */
      public Builder setVal1(int value) {
        
        val1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 val1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal1() {
        
        val1_ = 0;
        onChanged();
        return this;
      }

      private int val2_ ;
      /**
       * <code>int32 val2 = 2;</code>
       * @return The val2.
       */
      @java.lang.Override
      public int getVal2() {
        return val2_;
      }
      /**
       * <code>int32 val2 = 2;</code>
       * @param value The val2 to set.
       * @return This builder for chaining.
       */
      public Builder setVal2(int value) {
        
        val2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 val2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal2() {
        
        val2_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddRequest)
    }

    // @@protoc_insertion_point(class_scope:AddRequest)
    private static final com.coder4.homs.demo.HomsDemoOuterClass.AddRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.coder4.homs.demo.HomsDemoOuterClass.AddRequest();
    }

    public static com.coder4.homs.demo.HomsDemoOuterClass.AddRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddRequest>() {
      @java.lang.Override
      public AddRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.coder4.homs.demo.HomsDemoOuterClass.AddRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 val = 1;</code>
     * @return The val.
     */
    int getVal();
  }
  /**
   * Protobuf type {@code AddResponse}
   */
  public static final class AddResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddResponse)
      AddResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddResponse.newBuilder() to construct.
    private AddResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              val_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.class, com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    private int val_;
    /**
     * <code>int32 val = 1;</code>
     * @return The val.
     */
    @java.lang.Override
    public int getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (val_ != 0) {
        output.writeInt32(1, val_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (val_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.coder4.homs.demo.HomsDemoOuterClass.AddResponse)) {
        return super.equals(obj);
      }
      com.coder4.homs.demo.HomsDemoOuterClass.AddResponse other = (com.coder4.homs.demo.HomsDemoOuterClass.AddResponse) obj;

      if (getVal()
          != other.getVal()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + getVal();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.coder4.homs.demo.HomsDemoOuterClass.AddResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddResponse)
        com.coder4.homs.demo.HomsDemoOuterClass.AddResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.class, com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.Builder.class);
      }

      // Construct using com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        val_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.coder4.homs.demo.HomsDemoOuterClass.internal_static_AddResponse_descriptor;
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddResponse getDefaultInstanceForType() {
        return com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddResponse build() {
        com.coder4.homs.demo.HomsDemoOuterClass.AddResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.coder4.homs.demo.HomsDemoOuterClass.AddResponse buildPartial() {
        com.coder4.homs.demo.HomsDemoOuterClass.AddResponse result = new com.coder4.homs.demo.HomsDemoOuterClass.AddResponse(this);
        result.val_ = val_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.coder4.homs.demo.HomsDemoOuterClass.AddResponse) {
          return mergeFrom((com.coder4.homs.demo.HomsDemoOuterClass.AddResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.coder4.homs.demo.HomsDemoOuterClass.AddResponse other) {
        if (other == com.coder4.homs.demo.HomsDemoOuterClass.AddResponse.getDefaultInstance()) return this;
        if (other.getVal() != 0) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.coder4.homs.demo.HomsDemoOuterClass.AddResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.coder4.homs.demo.HomsDemoOuterClass.AddResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int val_ ;
      /**
       * <code>int32 val = 1;</code>
       * @return The val.
       */
      @java.lang.Override
      public int getVal() {
        return val_;
      }
      /**
       * <code>int32 val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(int value) {
        
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        
        val_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddResponse)
    }

    // @@protoc_insertion_point(class_scope:AddResponse)
    private static final com.coder4.homs.demo.HomsDemoOuterClass.AddResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.coder4.homs.demo.HomsDemoOuterClass.AddResponse();
    }

    public static com.coder4.homs.demo.HomsDemoOuterClass.AddResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddResponse>() {
      @java.lang.Override
      public AddResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.coder4.homs.demo.HomsDemoOuterClass.AddResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016HomsDemo.proto\"(\n\nAddRequest\022\014\n\004val1\030\001" +
      " \001(\005\022\014\n\004val2\030\002 \001(\005\"\032\n\013AddResponse\022\013\n\003val" +
      "\030\001 \001(\0052,\n\010HomsDemo\022 \n\003Add\022\013.AddRequest\032\014" +
      ".AddResponseB\026\n\024com.coder4.homs.demob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddRequest_descriptor,
        new java.lang.String[] { "Val1", "Val2", });
    internal_static_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
